



class ExcelCellTitle:
    CELL_TEST_CASE_ID = "A"
    CELL_TEST_CASE_TITLE = "B"
    CELL_REQUEST_METHOD = "C"
    CELL_REQUEST_URL = "D"
    CELL_TEST_CASE_EXECUTE_BRANCH = "E"
    CELL_FRONT_TEST_CASE_ID = "F"
    CELL_DATA_TYPE = "G"
    CELL_REGULAR = "H"
    CELL_DEPENDENT_FIELDS = "I"
    CELL_REQUEST_PARAMS = "J"
    CELL_EXPECT = "K"